apiVersion: v1
kind: Pod
metadata:
  name: audit-shadow
  namespace: arsl-lab
  labels:
    app.kubernetes.io/name: audit-shadow
    security.agent-runtime/role: identity-abuse
spec:
  serviceAccountName: compromised-agent
  automountServiceAccountToken: false
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tool
      image: busybox:1.36.1
      command: ["/bin/sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 32Mi
