apiVersion: v1
kind: Namespace
metadata:
  name: arsl-lab
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-tools
  namespace: arsl-lab
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: untrusted-runner
  namespace: arsl-lab
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: approved-tool
  namespace: arsl-lab
  labels:
    app.kubernetes.io/name: approved-tool
    security.agent-runtime/role: approved
spec:
  serviceAccountName: agent-tools
  automountServiceAccountToken: false
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tool
      image: busybox:1.36.1
      command: ["/bin/sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 32Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: shadow-runner
  namespace: arsl-lab
  labels:
    app.kubernetes.io/name: shadow-runner
    security.agent-runtime/role: untrusted
spec:
  serviceAccountName: untrusted-runner
  automountServiceAccountToken: false
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tool
      image: busybox:1.36.1
      command: ["/bin/sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 32Mi
